language: node_js
node_js:
  - 8.6.0

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script: yarn test:ci
    - stage: build project
      script: yarn build