version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.6.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:ci
  build:
    docker:
      - image: circleci/node:8.6.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn build
  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy to ravens-scans.com
          command: |
            apt-get update
            apt-get -qq install git-ftp
            echo "Initiating Push site ravens-scans.com"
            git ftp init --user $FTP_USER --passwd $FTP_PASSWORD ftp://ravens-scans.com/test_ci
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: ravens